dhmoi/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^$', views.home),
	url(r'dhmos_new/$', views.dhmospost_new, name='dhmos_new'),
	url(r'employee/$', views.employee, name="employee"),
	url(r'employee_new/$', views.employee_new, name='employee_new'),
	url(r'aithmata/$', views.aithmata, name="aithmata"),
	url(r'aithmata_new/', views.aithmata_new, name='aithmata_new'),
	url(r'service/$', views.service, name="service"),
	url(r'service_new/', views.service_new, name='service_new'),
	url(r'ergasies/$', views.ergasies, name='ergasies'),
	url(r'ergasia_new/', views.ergasia_new, name='ergasia_new'),
	url(r'adeia/', views.adeia, name='adeia'),
	url(r'adeia_new/', views.adeia_new, name='adeia_new'),
	url(r'update/ergasia/(?P<pk>\d+)/', views.ergasia_update, name='ergasia_update'),
	url(r'update/adeies/(?P<pk>\d+)/', views.adeia_update, name='adeia_update'),
	url(r'update/service/(?P<pk>\d+)/', views.service_update, name='service_update'),
	url(r'update/employee/(?P<pk>\d+)/', views.employee_update, name='employee_update'),
	url(r'update/dhmos/(?P<pk>\d+)/', views.dhmos_update, name='dhmos_update'),
	url(r'update/aithmata/(?P<pk>\d+)/', views.aithmata_update, name='aithmata_update'),
	url(r'delete/(?P<pk>\d+)/', views.delete_adeia, name='delete_adeia'),
	url(r'delete_aithmata/(?P<pk>\d+)/', views.delete_aithmata, name='delete_aithmata'),
	url(r'delete_employee/(?P<pk>\d+)/', views.delete_employee, name='delete_employee'),
	url(r'delete_ergasia/(?P<pk>\d+)/', views.delete_ergasia, name='delete_ergasia'),
	url(r'delete_home/(?P<pk>\d+)/', views.delete_home, name='delete_home'),
	url(r'delete_service/(?P<pk>\d+)/', views.delete_service, name='delete_service'),

]
#url(r'delete/(?P<pk>\d+)/', views.delete_adeia, name='delete_adeia'),

maziotis/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from dhmoi.views import home
from django.views.generic import TemplateView
from django.contrib.auth.views import logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('dhmoi.urls'), name='home'),
    url(r'^dhmoi/', include('dhmoi.urls')),
    url(r'^dhmos_new/', include('dhmoi.urls')),
    url(r'^employee/', include('dhmoi.urls')),
    url(r'^employee_new/', include('dhmoi.urls')),
    url(r'^aithmata/', include('dhmoi.urls')),
    url(r'^aithmata_new/', include('dhmoi.urls')),
    url(r'^service', include('dhmoi.urls')),
    url(r'^service_new/', include('dhmoi.urls')),
    url(r'^ergasies/', include('dhmoi.urls')),
    url(r'^ergasia_new/', include('dhmoi.urls')),
    url(r'^adeia/', include('dhmoi.urls')),
    url(r'^', include('dhmoi.urls')),
    url(r'^login/$', auth_views.login, {'template_name': 'registration/login.html'}),
    
    ]

dhmoi/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone

import datetime


import sys
reload(sys)
sys.setdefaultencoding('utf8')


type_choice = (
    ('laptop','Laptop'),
    ('desktop','Desktop'),
    ('tameiakh','Ταμειακή Μηχανή'),
    
    )

tmhma_choice = (
    ('1','Οικονομική'),
    ('2','Τεχνική'),
    ('3','Διοικητική'),
    ('4','Γραφείο Προσωπικού'),
    ('5','Μισθοδοσία'),
    ('6','Γραφείο Δημάρχου'),
    ('7','Τμήμα Πληροφορικής'),
    ('8','Ληξιαρχείο')
    )

job_choice = (
    ('TeamViewer','TeamViewer'),
    ('Επίσκεψη','Επίσκεψη'),
    ('Γραφείο','Γραφείο')
    )

employee_choice = (
    ('1','Αλέξης Μαυραγάνης'),
    ('2','Γιώργος Μαυραγάνης'),
    ('3','Κωστής Βυτινιώτης'),
    ('4','Αθανασία Καρακούση'),
    ('5','Κώστας Βυτινιώτης')
    )

adeia_choice = (
    ('1','Κανονική'),
    ('2','Αναρρωτική'),
    ('3','Εορταστική')
    )

app_choice = (
    ('ΤΑΠ','ΤΑΠ'),
    ('Μισθοδοσία','Μισθοδοσία'),
    ('Διαχείριση Προσωπικού','Διαχείριση Προσωπικού'),
    ('Λογιστική','Λογιστική'),
    ('Μητρώο Πολιτών','Μητρώο Πολιτών'),
    ('Ύδρευση','Ύδρευση'),
    ('Πρωτόκολλο','Πρωτόκολλο'),
    ('Διαύγεια','Διαύγεια'),
    ('Έσοδα','Έσοδα'),
    ('Κοιμητήρια','Κοιμητήρια'),
    ('ΚΟΚ','ΚΟΚ'),
    ('Δημοτικός φόρος','Δημοτικός φόρος'),
    ('Site','Site'),
    ('Πρακτικό','Πρακτικό'),
    )

class Dhmos(models.Model):
    name = models.CharField(max_length=100,verbose_name='Πελάτης', blank=False)
    phone = models.CharField(max_length=100, verbose_name='Τηλέφωνο', blank=False)
    fax = models.CharField(max_length=50, verbose_name='Fax', blank=True)
    teamviewer = models.CharField(max_length=60, verbose_name='TeamViewer', blank=True)
    email = models.EmailField(blank=True)
    website = models.URLField(max_length=250, blank=True, null=True)
    info = models.TextField(max_length=1000, verbose_name='Πληροφορίες', blank=True)
    

    class Meta:
        verbose_name = 'Πελάτες'
        verbose_name_plural = 'Πελάτες'
        ordering = ['id']
    def __str__(self):
                return self.name



class Employee(models.Model):
    dhmos = models.ForeignKey('Dhmos', on_delete=models.CASCADE, verbose_name='Δήμος', null=True)
    firstname = models.CharField(max_length=150, verbose_name='Όνομα', null=True)
    lastname = models.CharField(max_length=150, verbose_name='Επώνυμο', null=True)
    tmhma = models.CharField(max_length=100, choices= tmhma_choice, verbose_name='Υπηρεσία', blank=True)
    phone = models.CharField(max_length=100, verbose_name='Τηλέφωνο', blank=False)
    cellphone = models.CharField(max_length=30, verbose_name='Κινητό', blank=True)
    email = models.EmailField(blank=True)
    info = models.TextField(max_length=1000, verbose_name='Πληροφορίες', blank=True)

    class Meta:
        verbose_name = 'Στοιχεία Επικοινωνίας Πελατών'
        verbose_name_plural = 'Στοιχεία Επικοινωνίας Πελατών'
        
    def __str__(self):
                return self.lastname




class Service(models.Model):
    employee = models.ForeignKey('auth.User', verbose_name='Χρήστης', on_delete=models.CASCADE) 
    customername = models.CharField(max_length=150, verbose_name='Ονομα Πελάτη', null=False,blank=True)#first last
    phone = models.CharField(max_length=100, verbose_name='Τηλέφωνο Σταθερό', null=True,blank=True)
    cellphone = models.CharField(max_length=100, verbose_name='Κινητό Τηλέφωνο', null=True, blank=True)
    modelinfo = models.CharField(max_length=150,choices=type_choice, verbose_name='Τύπος', null=True,blank=True)
    serialnumber = models.CharField(max_length=100, verbose_name='S/N', null=True,blank=True)
    modeltype = models.CharField(max_length=150, verbose_name='Μοντέλο', null=True,blank=True)
    importdate = models.CharField(max_length=150,verbose_name='Ημ. Εισαγωγής',blank=True)
    info = models.TextField(max_length=500, verbose_name='Διάγνωση',null=True,blank=True)
    exportdate = models.CharField(max_length=150,verbose_name='Ημ. Παράδοσης',blank=True)
    cost = models.IntegerField(verbose_name='Κόστος επισκευής',blank=True)
    year = models.CharField(max_length=50, verbose_name='Έτος', null=False,blank=True)

    class Meta:
        verbose_name = 'Service'
        verbose_name_plural = 'Service'

    def __str__(self):
                return self.customername



class Ergasies(models.Model):
    dhmos = models.ForeignKey('Dhmos', on_delete=models.CASCADE, verbose_name='Πελάτης', default='-')
    importdate = models.DateField(verbose_name='Ημ. Κατ.')
    app = models.CharField(max_length=100, choices=app_choice,verbose_name='Εφαρμογή', blank=True)
    jobtype = models.CharField(max_length=100, choices=job_choice, verbose_name='Τύπος Εργασίας', default='TeamViewer')
    info = models.TextField(max_length=1000, verbose_name='Περιγραφή')
    text = models.TextField(max_length=1000, verbose_name='Σημειώσεις', blank=True)
    employee = models.ForeignKey('auth.User', max_length=100,  verbose_name='Υπάλληλος', default='-')#delete kai 
    time = models.CharField(max_length=20,verbose_name='Διάρκεια', default=0)
    name = models.CharField(max_length=100, verbose_name='Υπάλληλος Επικοιν.', null=True,help_text='Επώνυμο-Όνομα', blank=True)
    ticketid = models.CharField(max_length=50,verbose_name='Αίτημα OTS', blank=True)

    class Meta:
        verbose_name = 'Εργασίες'
        verbose_name_plural = 'Εργασίες'
        ordering = ['importdate']



class Aithmata(models.Model):
    dhmos = models.ForeignKey('Dhmos', on_delete=models.CASCADE, verbose_name='Δήμος')
    importdate = models.CharField(max_length=100,verbose_name='Ημ. Καταχώρησης')
    info = models.TextField(max_length=500, verbose_name='Περιγραφή')
    employee = models.CharField(max_length=100, verbose_name='Όν. Υπαλλήλου')
    assign = models.ForeignKey('auth.User', max_length=100, verbose_name='Χρέωση')
    closedate = models.CharField(max_length=100,verbose_name='Ημ. Κλεισίματος')

    class Meta:
        verbose_name = 'Αιτήματα'
        verbose_name_plural = 'Αιτήματα'


class Adeia(models.Model):
    employee = models.ForeignKey('auth.User',max_length=100, verbose_name='Υπάλληλος')
    adeiatype = models.CharField(max_length=50, choices=adeia_choice, verbose_name='Τύπος Άδειας', blank=True, default='-' )
    startdate = models.CharField(max_length=100,verbose_name='Από')
    enddate = models.CharField(max_length=100,verbose_name='Έως')
    createddate = models.CharField(max_length=100,verbose_name='Ημ. Δημουργίας')

    class Meta:
        verbose_name = 'Άδειες'
        verbose_name_plural = 'Άδειες'

   
    

dhmoi/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Ergasies, Dhmos, Employee, Service, Aithmata, Adeia
from django.contrib.auth.models import User
from django.forms import ModelChoiceField



class NameChoiceField(ModelChoiceField):

    def label_from_instance(self,obj):
        return '{lastname} {firstname}'.format(lastname=obj.lastname, firstname=obj.firstname)
        
class UserModelChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
         return '{last_name} {first_name}'.format(last_name=obj.last_name, first_name=obj.first_name)

class ErgasiaForm(forms.ModelForm):
    #name = forms.ModelChoiceField(required=False, queryset = Employee.objects.all().order_by('lastname'))
    
    name = NameChoiceField(queryset=Employee.objects.order_by('lastname'),label='Υπάλληλος Επικοιν.', required=False)
    employee = UserModelChoiceField(queryset=User.objects.order_by('last_name'), label='Υπάλληλος ACS')
    class Meta:
        
        model =  Ergasies
        fields = '__all__'
        fields = ['importdate','app','dhmos','name','jobtype','info','text','employee','time','ticketid']
        
  



class DhmosForm(forms.ModelForm):

    class Meta:
        model = Dhmos
        fields = '__all__'


class EmployeeForm(forms.ModelForm):

    class Meta:
        model = Employee
        fields = '__all__'


class AithmataForm(forms.ModelForm):
    assign = UserModelChoiceField(queryset=User.objects.order_by('last_name'), label='Χρέωση')
    class Meta:
        model = Aithmata
        fields = '__all__'


class ServiceForm(forms.ModelForm):
    employee = UserModelChoiceField(queryset=User.objects.order_by('last_name'), label='Υπάλληλος ACS')
    class Meta:
        model = Service
        fields = '__all__'


class AdeiaForm(forms.ModelForm):
    employee = UserModelChoiceField(queryset=User.objects.order_by('last_name'), label='Υπάλληλος ACS')
    class Meta:
        model = Adeia
        fields = '__all__'

dhmoi/templates/dhmoi/adeia_new.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}

<link rel="stylesheet"  href="{% static 'dhmoi/style.css' %}" />
    <h2 class="post-form" style="color:red; font-family: Courier New, monospace; text-align: center;"><b>Νέα Άδεια</b></h2></br>
    <form method="POST" class="post-form-adeia-new">{% csrf_token %}
        <div class="form-row">
        	<div class="form-group col-md-3 mb-0">
        		{{adeiaform.employee|as_crispy_field}}
        	</div>
        	<div class="form-group col-md-3 mb-0">
        		{{adeiaform.adeiatype|as_crispy_field}}
        	</div>
        	<div class="form-group col-md-3 mb-0">
        		{{adeiaform.startdate|as_crispy_field}}
        	</div>
        </div>
        <div class="form-row">
        	<div class="form-group col-md-3 mb-0">
        		{{adeiaform.enddate|as_crispy_field}}
        	</div>
        	<div class="form-group col-md-3 mb-0">
        		{{adeiaform.createddate|as_crispy_field}}
        	</div>
        </div>
        <div class="form-row" style="clear:both;">
        <button type="submit" class="save addnewbtn btn-success">Αποθήκευση</button>
    </div>
    </form>
{% endblock %}

dhmoi/templates/dhmoi/adeies.html
{% extends 'base.html' %}
{% load static %}
<head>
<link rel="stylesheet"  href="{% static 'dhmoi/style.css' %}" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
</head>
<body>
	{% block body %}
	<div class="header">
  <h2>ACS Services</h2>
  <h3>Άδειες</h3>
  </div></p>
<div class="form-row" style="clear:both;">
  <a href="{% url 'adeia_new' %}"  class="addnewbtn btn btn-info">Νέα Άδεια</a> 
    </div><br><br>
<table border="1" width="1600" id="myTable">
	<tr>
		<th>Υπάλληλος</th>
		<th>Τύπος Άδειας</th>
		<th>Αρχή</th>
		<th>Τέλος</th>
		<th>Ημ. Δημιουργίας</th>
		<th>Edit</th>
	</tr>
	{% for adeia in alladeies %}
	<tr>
		<td>{{adeia.employee.get_full_name}}</td>
		<td>{{adeia.get_adeiatype_display}}</td>
		<td>{{adeia.startdate}}</td>
		<td>{{adeia.enddate}}</td>
		<td>{{adeia.createddate}}</td>
		<td style="width:7%;"><a class="btn btn-default" href="{% url 'adeia_update' pk=adeia.pk %}"><span class="glyphicon glyphicon-pencil" style="color: green;"></span></a>|<a class="btn btn-default" onclick="return confirm('Είστε σίγουρος/η για την διαγραφή;');" href="{% url 'delete_adeia' pk=adeia.pk %}"><span class="glyphicon glyphicon-trash" style="color: red;"></span></a></td>
	</tr>
	{% endfor %}

</table>

	{% endblock %}
	
</body>

dhmoi/templates/dhmoi/employee.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}
<head>
<link rel="stylesheet"  href="{% static 'dhmoi/style.css' %}" />


</head>
<body>
	{% block body %}
	<div class="header">
  <h2>ACS Services</h2>
  <h3>Υπάλληλος</h3>

</div></p>
<div class="form-row" style="clear:both;">
<a href="{% url 'employee_new' %}"  class="addnewbtn btn btn-primary">Νέος Υπάλληλος</a> 
  <a href="{% url 'dhmos_new' %}" target="_blank" class="addnewbtn btn btn-warning">Νέος Πελάτης</a>
	   
	</div><br><br>
	<form method="get">
    <div class="well">
      <h4 style="margin-top: 0">Αναζήτηση</h4>
      <div class="row">
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.dhmos.label_tag }}
          {% render_field filter.form.dhmos class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.firstname.label_tag }}
          {% render_field filter.form.firstname class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.lastname.label_tag }}
          {% render_field filter.form.lastname class="form-control" %}
        </div>
        
            
          </div>
             <button type="submit" class="btn btn-primary">
        <span class="glyphicon glyphicon-search"></span> Αναζήτηση
      </button>
        </div>

      </div>
     
    </div>
  </form>
<table border="1" class="myTable" id="employeeTable" >
	<tr>
		<th>Πελάτης</th>
		<th>Επώνυμο</th>
		<th>Όνομα</th>
		<th>Τμήμα</th>
		<th>Τηλέφωνο</th>
		<th>Κινητό</th>
		<th>Email</th>
		<th>Edit</th>
	</tr>
	{% for employee in filter.qs %}
	<tr>
		<td>{{employee.dhmos}}</td>
		<td>{{employee.lastname}}</td>
		<td>{{employee.firstname}}</td>
		<td>{{employee.get_tmhma_display}}</td>
		<td>{{employee.phone}}</td>
		<td>{{employee.cellphone}}</td>
		<td><font color="blue">{{employee.email}}</font></td>
		<td style="width:7%;"><a class="btn btn-default" href="{% url 'employee_update' pk=employee.pk %}"><span class="glyphicon glyphicon-pencil" style="color: green;"></span></a>|<a class="btn btn-default" onclick="return confirm('Είστε σίγουρος/η για την διαγραφή;');" href="{% url 'delete_employee' pk=employee.pk %}"><span class="glyphicon glyphicon-trash" style="color: red;"></span></a></td>
	</tr>
	{% endfor %}
</table>
<script>
	// get the table element
var $table = document.getElementById("employeeTable"),
// number of rows per page
$n = 10,
// number of rows of the table
$rowCount = $table.rows.length,
// get the first cell's tag name (in the first row)
$firstRow = $table.rows[0].firstElementChild.tagName,
// boolean var to check if table has a head row
$hasHead = ($firstRow === "TH"),
// an array to hold each row
$tr = [],
// loop counters, to start count from rows[1] (2nd row) if the first row has a head tag
$i,$ii,$j = ($hasHead)?1:0,
// holds the first row if it has a (<TH>) & nothing if (<TD>)
$th = ($hasHead?$table.rows[(0)].outerHTML:"");
// count the number of pages
var $pageCount = Math.ceil($rowCount / $n);
// if we had one page only, then we have nothing to do ..
if ($pageCount > 1) {
    // assign each row outHTML (tag name & innerHTML) to the array
    for ($i = $j,$ii = 0; $i < $rowCount; $i++, $ii++)
        $tr[$ii] = $table.rows[$i].outerHTML;
    // create a div block to hold the buttons
    $table.insertAdjacentHTML("afterend","<div id='buttons'></div");
    // the first sort, default page is the first one
    sort(1);
}

// ($p) is the selected page number. it will be generated when a user clicks a button
function sort($p) {
    /* create ($rows) a variable to hold the group of rows
    ** to be displayed on the selected page,
    ** ($s) the start point .. the first row in each page, Do The Math
    */
    var $rows = $th,$s = (($n * $p)-$n);
    for ($i = $s; $i < ($s+$n) && $i < $tr.length; $i++)
        $rows += $tr[$i];
    
    // now the table has a processed group of rows ..
    $table.innerHTML = $rows;
    // create the pagination buttons
    document.getElementById("buttons").innerHTML = pageButtons($pageCount,$p);
    // CSS Stuff
    document.getElementById("id"+$p).setAttribute("class","active");
}


// ($pCount) : number of pages,($cur) : current page, the selected one ..
function pageButtons($pCount,$cur) {
    /* this variables will disable the "Prev" button on 1st page
       and "next" button on the last one */
    var $prevDis = ($cur == 1)?"disabled":"",
        $nextDis = ($cur == $pCount)?"disabled":"",
        /* this ($buttons) will hold every single button needed
        ** it will creates each button and sets the onclick attribute
        ** to the "sort" function with a special ($p) number..
        */
        $buttons = "<input type='button' value='&lt;&lt; Προηγ.' onclick='sort("+($cur - 1)+")' "+$prevDis+">";
    for ($i=1; $i<=$pCount;$i++)
        $buttons += "<input type='button' id='id"+$i+"'value='"+$i+"' onclick='sort("+$i+")'>";
    $buttons += "<input type='button' value='Επόμ. &gt;&gt;' onclick='sort("+($cur + 1)+")' "+$nextDis+">";
    return $buttons;
}
</script>
	{% endblock %}
	
</body>


	

dhmoi/templates/dhmoi/ergasies.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}
<head>
<link rel="stylesheet"  href="{% static 'dhmoi/style.css' %}" />
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="src/jquery.table2excel.js"></script>
</head>
<body>
	{% block body %}
	<div class="header">
  <h2>ACS Services</h2>
  <h3>Εργασίες</h3>
</div></p>
<div class="form-row" style="clear:both;">
<a href="{% url 'ergasia_new' %}"  class="addnewbtn btn btn-info">Νέα Εργασία</a> 
  <a href="{% url 'dhmos_new' %}" target="_blank" class="addnewbtn btn btn-warning">Νέος Πελάτης</a>
  <a href="{% url 'employee_new' %}" target="_blank" class="addnewbtn btn btn-primary">Νέος Υπάλληλος</a> 
     <a href="#"  class="addnewbtn btn btn-primary">Εξαγωγή</a> 
    </div><br><br>
    <form method="get">
    <div class="well">
      <h4 style="margin-top: 0">Αναζήτηση</h4>
      <div class="row">
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.dhmos.label_tag }}
          {% render_field filter.form.dhmos class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.app.label_tag }}
          {% render_field filter.form.app class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.employee.label_tag }}
          {% render_field filter.form.employee class="form-control" %}
        </div>
      
            
          </div>
             <button type="submit" class="btn btn-primary">
        <span class="glyphicon glyphicon-search"></span> Αναζήτηση
      </button>
        </div>

      </div>
     
    </div>
<table border="1" class="myTable" id="myTable" >
	<tr>
		<th>Κατ.</th>
		<th>Εφαρμογή</th>
		<th>Πελάτης</th>
		<th>Υπ.Επικοιν.</th>
		<th>Εργασία</th>
		<th>Περιγραφή</th>
		<th>ACS</th>
		<th>Διάρκεια</th>
		<th>ID Αιτ.</th>
		<th>Edit</th>
	</tr>
	{% for ergasies in filter.qs %}
	<tr>
		<td>{{ergasies.importdate|date:"d/m/Y"}}</td>
		<td>{{ergasies.get_app_display}}</td>
		<td>{{ergasies.dhmos}}</td>
		<td>{{ergasies.name}}</td>
		<td>{{ergasies.get_jobtype_display}}</td>
		<td>{{ergasies.info}}</td>
		<td>{{ergasies.employee.get_full_name}}</td>
		<td>{{ergasies.time}}</td>
		<td><font color="red">{{ergasies.ticketid}}</font></td>
		<td style="width:7%;"><a class="btn btn-default" href="{% url 'ergasia_update' pk=ergasies.pk %}"><span class="glyphicon glyphicon-pencil" style="color: green;"></span></a>|<a class="btn btn-default" onclick="return confirm('Είστε σίγουρος/η για την διαγραφή;');" href="{% url 'delete_ergasia' pk=ergasies.pk %}"><span class="glyphicon glyphicon-trash" style="color: red;"></span></a></td>
	</tr>
	{% endfor %}
</table>
<script>
	// get the table element
var $table = document.getElementById("myTable"),
// number of rows per page
$n = 20,
// number of rows of the table
$rowCount = $table.rows.length,
// get the first cell's tag name (in the first row)
$firstRow = $table.rows[0].firstElementChild.tagName,
// boolean var to check if table has a head row
$hasHead = ($firstRow === "TH"),
// an array to hold each row
$tr = [],
// loop counters, to start count from rows[1] (2nd row) if the first row has a head tag
$i,$ii,$j = ($hasHead)?1:0,
// holds the first row if it has a (<TH>) & nothing if (<TD>)
$th = ($hasHead?$table.rows[(0)].outerHTML:"");
// count the number of pages
var $pageCount = Math.ceil($rowCount / $n);
// if we had one page only, then we have nothing to do ..
if ($pageCount > 1) {
    // assign each row outHTML (tag name & innerHTML) to the array
    for ($i = $j,$ii = 0; $i < $rowCount; $i++, $ii++)
        $tr[$ii] = $table.rows[$i].outerHTML;
    // create a div block to hold the buttons
    $table.insertAdjacentHTML("afterend","<div id='buttons'></div");
    // the first sort, default page is the first one
    sort(1);
}

// ($p) is the selected page number. it will be generated when a user clicks a button
function sort($p) {
    /* create ($rows) a variable to hold the group of rows
    ** to be displayed on the selected page,
    ** ($s) the start point .. the first row in each page, Do The Math
    */
    var $rows = $th,$s = (($n * $p)-$n);
    for ($i = $s; $i < ($s+$n) && $i < $tr.length; $i++)
        $rows += $tr[$i];
    
    // now the table has a processed group of rows ..
    $table.innerHTML = $rows;
    // create the pagination buttons
    document.getElementById("buttons").innerHTML = pageButtons($pageCount,$p);
    // CSS Stuff
    document.getElementById("id"+$p).setAttribute("class","active");
}


// ($pCount) : number of pages,($cur) : current page, the selected one ..
function pageButtons($pCount,$cur) {
    /* this variables will disable the "Prev" button on 1st page
       and "next" button on the last one */
    var $prevDis = ($cur == 1)?"disabled":"",
        $nextDis = ($cur == $pCount)?"disabled":"",
        /* this ($buttons) will hold every single button needed
        ** it will creates each button and sets the onclick attribute
        ** to the "sort" function with a special ($p) number..
        */
        $buttons = "<input type='button' value='&lt;&lt; Prev' onclick='sort("+($cur - 1)+")' "+$prevDis+">";
    for ($i=1; $i<=$pCount;$i++)
        $buttons += "<input type='button' id='id"+$i+"'value='"+$i+"' onclick='sort("+$i+")'>";
    $buttons += "<input type='button' value='Next &gt;&gt;' onclick='sort("+($cur + 1)+")' "+$nextDis+">";
    return $buttons;
}
</script>
	{% endblock %}
	
</body>